"""
Reusable presentation primitives for the Streamlit dashboard.

Public API:
  inject_global_styles()          -- injects the stylesheet (re-exported from styles.py)
  render_hero(...)                -- cinematic landing hero (Overview only)
  render_page_header(...)         -- lighter page banner
  render_sidebar_brand(...)       -- sidebar wordmark (image-based)
  render_glass_card(title, body)  -- small HTML glass card
  render_explainer_card(...)      -- explanation-first card; live value lives in the tooltip
  plotly_layout(**overrides)      -- shared Plotly layout dict
  style_plotly(fig, **overrides)  -- apply theme to a Plotly figure in one call
  matplotlib_dark(fig, ax)        -- retheme a matplotlib axes to dark

The BackgroundPaths SVG motif is generated by `_build_paths_svg()` using the
same formula as the React reference, so the geometry matches exactly. Motion
is driven by CSS keyframes (see web/styles.py) — no JavaScript needed.
"""

from __future__ import annotations

import base64 as _base64
import html as _html
import os as _os
from typing import Iterable, Optional, Sequence, Tuple

import streamlit as st

from web.styles import inject_global_styles as _inject_global_styles
from web.theme import CHART_PALETTE, FONT_STACK, PALETTE

# Re-export so callers can do `from web.ui import inject_global_styles`
inject_global_styles = _inject_global_styles

# ---------------------------------------------------------------------------
# Background paths SVG generator (port of the React BackgroundPaths formula)
# ---------------------------------------------------------------------------

def _build_paths_svg(
    *,
    count: int = 36,
    variant: str = "hero",
) -> str:
    """
    Build the SVG <path> list for the background-paths motif.

    Parameters
    ----------
    count : int
        Paths per orientation. 36 matches the React reference.
    variant : "hero" | "header"
        "hero"   — full range of opacities and widths; longer durations.
        "header" — compressed, subtler for secondary pages.

    Each path carries CSS custom properties (--op, --dur, --d) consumed by
    the keyframes in web/styles.py.
    """
    lines: list[str] = []
    for position in (1, -1):
        for i in range(count):
            d = (
                f"M-{380 - i * 5 * position} -{189 + i * 6}"
                f"C-{380 - i * 5 * position} -{189 + i * 6} "
                f"-{312 - i * 5 * position} {216 - i * 6} "
                f"{152 - i * 5 * position} {343 - i * 6}"
                f"C{616 - i * 5 * position} {470 - i * 6} "
                f"{684 - i * 5 * position} {875 - i * 6} "
                f"{684 - i * 5 * position} {875 - i * 6}"
            )
            if variant == "header":
                opacity = 0.10 + i * 0.012
                width = 0.4 + i * 0.025
                dur = 26 + ((i * 7 + (0 if position == 1 else 11)) % 12)
            else:  # hero
                opacity = 0.10 + i * 0.018
                width = 0.5 + i * 0.030
                dur = 20 + ((i * 13 + (0 if position == 1 else 7)) % 10)

            delay = (i * 0.09 + (0 if position == 1 else 0.4)) % 6
            lines.append(
                f'<path d="{d}" '
                f'stroke-width="{width:.2f}" '
                f'style="--op:{opacity:.3f};--dur:{dur}s;--d:{delay:.2f}s;'
                f'opacity:{opacity:.3f};" />'
            )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Staggered-letter title
# ---------------------------------------------------------------------------

def _split_letters(title: str, base_delay_ms: int = 220) -> str:
    """
    Split `title` into word spans, each containing per-letter spans with
    staggered animation delays. Safe-encodes user text.
    """
    words = title.split(" ")
    html_out: list[str] = []
    for wi, word in enumerate(words):
        letter_spans: list[str] = []
        for li, letter in enumerate(word):
            delay = base_delay_ms + wi * 95 + li * 34
            letter_spans.append(
                f'<span class="ar-letter" style="--delay:{delay}ms">'
                f'{_html.escape(letter)}</span>'
            )
        html_out.append(f'<span class="ar-word">{"".join(letter_spans)}</span>')
    return "".join(html_out)


# ---------------------------------------------------------------------------
# Hero
# ---------------------------------------------------------------------------

def render_hero(
    title: str,
    *,
    eyebrow: Optional[str] = None,
    subtitle: Optional[str] = None,
    stats: Optional[Sequence[Tuple[str, str]]] = None,
) -> None:
    """
    Render the cinematic landing hero (Overview page only).

    Args:
        title:     Short title, 2–4 words recommended. Animated per-letter.
        eyebrow:   Optional small label above the title (pill style).
        subtitle:  Optional subtitle below the title.
        stats:     Optional list of (value, label) tuples rendered as a stat row.
    """
    eyebrow_html = ""
    if eyebrow:
        eyebrow_html = (
            f'<div class="ar-eyebrow">{_html.escape(eyebrow)}</div>'
        )

    subtitle_html = ""
    if subtitle:
        subtitle_html = (
            f'<p class="ar-hero-subtitle">{_html.escape(subtitle)}</p>'
        )

    stats_html = ""
    if stats:
        items = "".join(
            f'<div class="ar-hero-stat">'
            f'<span class="ar-hero-stat-value">{_html.escape(v)}</span>'
            f'<span class="ar-hero-stat-label">{_html.escape(lbl)}</span>'
            f'</div>'
            for v, lbl in stats
        )
        # Wrap the stat row in an opaque glass panel so the animated paths
        # underneath can't undermine readability.
        stats_html = f'<div class="ar-hero-stats-panel"><div class="ar-hero-stats">{items}</div></div>'

    title_html = _split_letters(title)
    paths_svg = _build_paths_svg(variant="hero")

    html = f'''
<div class="ar-hero">
  <svg class="ar-hero-paths" viewBox="0 0 696 316"
       preserveAspectRatio="xMidYMid slice" aria-hidden="true">
    <title>Background Paths</title>
    {paths_svg}
  </svg>
  <div class="ar-hero-content">
    {eyebrow_html}
    <h1 class="ar-hero-title">{title_html}</h1>
    {subtitle_html}
    {stats_html}
  </div>
</div>
'''
    st.markdown(html, unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Page header (non-Overview pages)
# ---------------------------------------------------------------------------

def render_page_header(
    title: str,
    *,
    eyebrow: Optional[str] = None,
    subtitle: Optional[str] = None,
) -> None:
    """
    Lighter page banner used by every page except Overview.

    Keeps the animated-paths motif in the background at reduced opacity, with
    a gradient-text title. No per-letter stagger (reserved for the hero) — a
    single restrained entrance so the dashboard doesn't feel like 6 landings.
    """
    eyebrow_html = ""
    if eyebrow:
        eyebrow_html = (
            f'<div class="ar-page-eyebrow">{_html.escape(eyebrow)}</div>'
        )

    subtitle_html = ""
    if subtitle:
        subtitle_html = (
            f'<p class="ar-page-subtitle">{subtitle}</p>'  # allow markdown-ish in subtitle
        )

    paths_svg = _build_paths_svg(variant="header")

    html = f'''
<div class="ar-page-header">
  <svg class="ar-page-header-paths" viewBox="0 0 696 180"
       preserveAspectRatio="xMidYMid slice" aria-hidden="true">
    <title>Background Paths</title>
    {paths_svg}
  </svg>
  <div class="ar-page-header-content">
    {eyebrow_html}
    <h1 class="ar-page-title">{_html.escape(title)}</h1>
    {subtitle_html}
  </div>
</div>
'''
    st.markdown(html, unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Sidebar brand wordmark
# ---------------------------------------------------------------------------

_ASSETS_DIR = _os.path.join(_os.path.dirname(__file__), "assets")
_SIDEBAR_BRAND_PATH = _os.path.join(_ASSETS_DIR, "sidebar-brand.png")


def _encode_image_as_data_uri(path: str) -> Optional[str]:
    """Read a PNG from disk and return a base64 data URI, or None if missing."""
    if not _os.path.isfile(path):
        return None
    with open(path, "rb") as f:
        payload = _base64.b64encode(f.read()).decode("ascii")
    return f"data:image/png;base64,{payload}"


def render_sidebar_brand() -> None:
    """
    Render the sidebar wordmark using ``web/assets/sidebar-brand.png``.

    The PNG is transparent, so it sits cleanly on the dark sidebar gradient.
    Falls back to a text wordmark if the asset is missing so the app still
    renders on a fresh clone before the asset is placed.
    """
    data_uri = _encode_image_as_data_uri(_SIDEBAR_BRAND_PATH)
    if data_uri:
        st.sidebar.markdown(
            f'''
<div class="ar-sidebar-brand">
  <img src="{data_uri}" alt="Amazon Reviews" />
  <div class="ar-sidebar-brand-kicker">Reviews Analytics Dashboard</div>
</div>
''',
            unsafe_allow_html=True,
        )
        return

    # Asset missing — fall back to a minimal text wordmark so the app still
    # boots on a fresh clone before web/assets/sidebar-brand.png is placed.
    st.sidebar.markdown(
        '''
<div class="ar-sidebar-brand ar-sidebar-brand-fallback">
  <div class="ar-sidebar-brand-title">Amazon Reviews</div>
  <div class="ar-sidebar-brand-kicker">Reviews Analytics Dashboard</div>
</div>
''',
        unsafe_allow_html=True,
    )


def render_sidebar_section_label(text: str) -> None:
    """Render a small uppercase section label in the sidebar."""
    st.sidebar.markdown(
        f'<div style="font-size: 10.5px; text-transform: uppercase; '
        f'letter-spacing: 0.18em; color: rgba(238,240,246,0.45); '
        f'margin: 1.1rem 0 0.5rem 0.2rem; font-weight: 500;">{_html.escape(text)}</div>',
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# Inline glass card (for editorial text blocks)
# ---------------------------------------------------------------------------

def render_glass_card(title: Optional[str], body_html: str) -> None:
    """Render an HTML glass card. `body_html` is used as-is — caller escapes."""
    title_html = ""
    if title:
        title_html = f'<div class="ar-card-title">{_html.escape(title)}</div>'
    st.markdown(
        f'<div class="ar-card">{title_html}'
        f'<div class="ar-card-body">{body_html}</div></div>',
        unsafe_allow_html=True,
    )


def render_explainer_card(
    name: str,
    explanation: str,
    *,
    value: str,
    definition: Optional[str] = None,
) -> None:
    """
    Explanation-first card. The face shows the metric name and a short
    plain-language description; the live value (plus optional extended
    definition) is revealed by hovering the "?" help icon in the top-right
    corner — mirroring the ``st.metric(..., help="...")`` "?" affordance on
    the Category Detail page.
    """
    name_esc = _html.escape(name)
    explanation_esc = _html.escape(explanation)
    value_esc = _html.escape(value)

    # Tooltip leads with the numerical value (what the user wants on hover);
    # the definition follows as supporting context. Newlines are encoded as
    # &#10; so a blank line inside the HTML attribute can't end the markdown
    # block — that bug rendered the tag as plain text in the card body.
    if definition:
        def_esc = _html.escape(definition.strip())
        tooltip_attr = f"Current value: {value_esc}&#10;&#10;{def_esc}"
    else:
        tooltip_attr = f"Current value: {value_esc}"

    # Single-line HTML (no embedded newlines) so Streamlit's markdown parser
    # treats the whole card as one raw HTML block.
    html_str = (
        f'<div class="ar-explainer-card">'
        f'<div class="ar-explainer-label">{name_esc}</div>'
        f'<div class="ar-explainer-body">{explanation_esc}</div>'
        f'<span class="ar-explainer-help" tabindex="0" '
        f'data-tooltip="{tooltip_attr}" '
        f'aria-label="More info about {name_esc}">?</span>'
        f'</div>'
    )
    st.markdown(html_str, unsafe_allow_html=True)


def render_divider() -> None:
    """Themed divider (replaces st.markdown('---'))."""
    st.markdown('<hr class="ar-divider" />', unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Plotly theming
# ---------------------------------------------------------------------------

def plotly_layout(**overrides) -> dict:
    """Shared Plotly layout dict. Pass any kwarg to override specific keys."""
    base = dict(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(
            family=FONT_STACK,
            color=PALETTE["text_muted"],
            size=12.5,
        ),
        title=dict(
            font=dict(
                family=FONT_STACK,
                size=15,
                color=PALETTE["text"],
            ),
            x=0.01,
            xanchor="left",
            y=0.97,
            yanchor="top",
        ),
        margin=dict(l=10, r=10, t=54, b=10),
        xaxis=dict(
            gridcolor="rgba(255,255,255,0.05)",
            zerolinecolor="rgba(255,255,255,0.08)",
            linecolor="rgba(255,255,255,0.12)",
            tickfont=dict(size=11, color=PALETTE["text_muted"]),
            title=dict(font=dict(size=12, color=PALETTE["text_muted"])),
        ),
        yaxis=dict(
            gridcolor="rgba(255,255,255,0.05)",
            zerolinecolor="rgba(255,255,255,0.08)",
            linecolor="rgba(255,255,255,0.12)",
            tickfont=dict(size=11, color=PALETTE["text_muted"]),
            title=dict(font=dict(size=12, color=PALETTE["text_muted"])),
        ),
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            font=dict(color=PALETTE["text_muted"], size=11),
            bordercolor="rgba(255,255,255,0.08)",
        ),
        hoverlabel=dict(
            bgcolor=PALETTE["bg_elev"],
            bordercolor=PALETTE["border_strong"],
            font=dict(family=FONT_STACK, color=PALETTE["text"], size=12),
        ),
        colorway=CHART_PALETTE,
    )
    # Nested overrides: let callers pass e.g. margin=dict(t=30) without losing
    # the other defaults. We merge shallowly for dict values.
    for k, v in overrides.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            merged = dict(base[k])
            merged.update(v)
            base[k] = merged
        else:
            base[k] = v
    return base


def style_plotly(fig, **overrides):
    """Apply shared theming to a Plotly figure. Returns the figure."""
    fig.update_layout(**plotly_layout(**overrides))
    # Restyle colorbars to match dark theme
    fig.update_coloraxes(
        colorbar=dict(
            tickfont=dict(color=PALETTE["text_muted"], size=10.5),
            outlinewidth=0,
            thickness=12,
            len=0.85,
        )
    )
    return fig


# ---------------------------------------------------------------------------
# Matplotlib dark treatment (used by the network graph + cluster diagnostics)
# ---------------------------------------------------------------------------

def mpl_color(color: str) -> Tuple[float, float, float, float] | str:
    """
    Convert a CSS-style ``rgba(r, g, b, a)`` or ``rgb(r, g, b)`` string to the
    0-1 float tuple matplotlib accepts. Hex strings and named colors are
    passed through unchanged. Matplotlib rejects CSS-style ``rgba(...)`` —
    this shim lets us reuse the Plotly-oriented PALETTE values here.
    """
    s = color.strip()
    if s.startswith(("rgba(", "rgb(")) and s.endswith(")"):
        inner = s[s.index("(") + 1 : -1]
        parts = [p.strip() for p in inner.split(",")]
        try:
            r = float(parts[0]) / 255.0
            g = float(parts[1]) / 255.0
            b = float(parts[2]) / 255.0
            a = float(parts[3]) if len(parts) == 4 else 1.0
            return (max(0.0, min(1.0, r)),
                    max(0.0, min(1.0, g)),
                    max(0.0, min(1.0, b)),
                    max(0.0, min(1.0, a)))
        except (ValueError, IndexError):
            return s
    return s


def matplotlib_dark(fig, ax) -> None:
    """Retheme a matplotlib axes to the dashboard's dark palette."""
    text_muted = mpl_color(PALETTE["text_muted"])
    text = mpl_color(PALETTE["text"])
    border = mpl_color(PALETTE["border"])
    grid = mpl_color("rgba(255,255,255,0.05)")

    fig.patch.set_facecolor("#12121a")
    ax.set_facecolor("#12121a")
    ax.tick_params(colors=text_muted, labelsize=9)
    for spine in ax.spines.values():
        spine.set_color(border)
        spine.set_linewidth(0.8)
    ax.xaxis.label.set_color(text_muted)
    ax.yaxis.label.set_color(text_muted)
    if ax.get_title():
        ax.set_title(ax.get_title(), color=text, fontsize=12, fontweight="600")
    ax.grid(True, color=grid, linewidth=0.8)
